"""Index writer — upserts embedded DocumentChunks into Qdrant.

Each chunk becomes a Qdrant point with:
- **id**: the chunk's deterministic id (from DocumentChunk.id)
- **vector**: named dense vector ``"dense"`` (768-d) + named sparse vector
  ``"text"`` (BM25-style, generated by the embedder's sparse function)
- **payload**: the chunk metadata (title, source_url, section,
  last_modified, chunk_index, parent_doc_id) plus the chunk ``content``
  for retrieval display and context assembly.

Upserts are batched (default 64 points per request) to keep Qdrant
requests efficient. Stale chunks from a re-indexed document are deleted
by ``parent_doc_id`` filter before the new chunks are upserted — this
is the incremental-sync deletion strategy from the architecture doc.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from qdrant_client import QdrantClient
from qdrant_client.http.exceptions import UnexpectedResponse
from qdrant_client.models import (
    FieldCondition,
    Filter,
    MatchValue,
    PointStruct,
    SparseVector,
)

from ingestion.embedder import sparse_embed_batch
from rag.qdrant_collection import COLLECTION_NAME, SPARSE_VECTOR_NAME, VECTOR_NAME

if TYPE_CHECKING:
    from schemas.documents import DocumentChunk

logger = logging.getLogger(__name__)

DEFAULT_BATCH_SIZE: int = 64
"""Points per Qdrant upsert request. Tuned for a small local corpus."""


class IndexWriter:
    """Wraps a QdrantClient for chunk upsert + stale-chunk deletion."""

    def __init__(
        self,
        client: QdrantClient,
        collection_name: str = COLLECTION_NAME,
        batch_size: int = DEFAULT_BATCH_SIZE,
    ) -> None:
        self.client = client
        self.collection_name = collection_name
        self.batch_size = batch_size

    # ── stale chunk deletion ──────────────────────────────────────────

    def delete_by_parent(self, parent_doc_id: str) -> int:
        """Delete all chunks belonging to a parent document.

        Used during incremental re-index: delete the old chunks before
        upserting the new ones so no stale fragments remain.

        Returns the number of points deleted (best-effort; may be 0 if
        the collection is empty or the doc was never indexed).
        """
        flt = Filter(
            must=[
                FieldCondition(
                    key="parent_doc_id",
                    match=MatchValue(value=parent_doc_id),
                )
            ]
        )
        try:
            result = self.client.delete(
                collection_name=self.collection_name,
                points_selector=flt,
                wait=True,
            )
            logger.info(
                "Deleted chunks for parent_doc_id=%s (operation_id=%s)",
                parent_doc_id,
                getattr(result, "operation_id", "?"),
            )
            return 0  # Qdrant delete doesn't return a count; 0 = "no error"
        except UnexpectedResponse as exc:
            if exc.status_code == 404:
                logger.debug("Collection %s not found during delete; skipping", self.collection_name)
                return 0
            raise

    # ── upsert ────────────────────────────────────────────────────────

    def upsert_chunks(self, chunks: list["DocumentChunk"]) -> int:
        """Embed (sparse) + upsert a list of DocumentChunks.

        The dense embeddings must already be set on each chunk
        (``chunk.embedding``). Sparse vectors are generated here from the
        chunk content because they are cheap (pure-Python tokenizer) and
        don't require an Ollama call.

        Returns the number of points upserted.
        """
        if not chunks:
            return 0

        # Generate sparse vectors from chunk content.
        sparse_vectors = sparse_embed_batch([c.content for c in chunks])

        upserted = 0
        for start in range(0, len(chunks), self.batch_size):
            batch = chunks[start : start + self.batch_size]
            batch_sparse = sparse_vectors[start : start + self.batch_size]
            points = [
                self._build_point(chunk, sparse)
                for chunk, sparse in zip(batch, batch_sparse)
            ]
            self.client.upsert(
                collection_name=self.collection_name,
                points=points,
                wait=True,
            )
            upserted += len(points)
            logger.debug(
                "Upserted batch %d-%d/%d into %s",
                start,
                start + len(points),
                len(chunks),
                self.collection_name,
            )
        logger.info("Upserted %d chunks into %s", upserted, self.collection_name)
        return upserted

    def _build_point(self, chunk: "DocumentChunk", sparse: SparseVector) -> PointStruct:
        """Build a Qdrant PointStruct from a chunk + its sparse vector."""
        if chunk.embedding is None:
            raise ValueError(
                f"Chunk {chunk.id} has no dense embedding — call the "
                "Embedder before upserting."
            )
        payload = chunk.to_payload()
        return PointStruct(
            id=chunk.id,
            vector={
                VECTOR_NAME: chunk.embedding,
                SPARSE_VECTOR_NAME: sparse,
            },
            payload=payload,
        )
